export FLASK_SECRET_KEY="ABCDEFG"

export YELP_CONSUMER_KEY="3ntG-6W5C9qnOSQ6QY1ifQ"
export YELP_CONSUMER_SECRET="pYj6X0htclw37_MPafiNkizc2cI"
export YELP_ACCESS_TOKEN_KEY="vmUo0Fon4ay-fmobBYSpezL-vgB9JCYd"
export YELP_ACCESS_TOKEN_SECRET="v-i0Kl64JKTvIGM3inuIPgos-QM"

export EVENTBRITE_KEY="JXPOFPSSCU4OQGRAG5RH"

export TWILIO_ACCOUNT_SID="JXPOFPSSCU4OQGRAG5RH"
export TWILIO_AUTH_TOKEN="JXPOFPSSCU4OQGRAG5RH" 